[[language]]
name = "python"
auto-format = true

[[language]]
name = "vhdl"
formatter.command = "vhdl_fmt.sh"

[[language]]
name = "typescript"
roots = ["deno.json", "deno.jsonc", "package.json"]
auto-format = true
language-servers = ["deno-lsp"]

[[language]]
name = "javascript"
roots = ["deno.json", "deno.jsonc", "package.json"]
auto-format = true
language-servers = ["deno-lsp"]

[[language]]
name = "bash"
indent = { unit = "    ", tab-width = 4 }
formatter = { command = "sed", args = ["s/[[:space:]]\\+$//"] }
auto-format = true

[[language]]
name = "mail"
text-width = 72

[[language]]
name = "openscad"
auto-format = true

[[language]]
name = "typst"
language-servers = ["tinymist", "typos"]

# -------- language servers -------- #

[language-server.rust-analyzer]
config.cargo.targetDir = true
config.check.command = "clippy"
config.imports.granularity.group = "item"
# too aggressive for existing projects without nightly formatting
# config.rustfmt.extraArgs = ["+nightly"]

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
config.deno.enable = true

[language-server.typos]
command = "typos-lsp"
