[language-server.rust-analyzer]
config.cargo.targetDir = true
config.check.command = "clippy"

[[language]]
name = "python"
auto-format = true

[[language]]
name = "vhdl"
formatter.command = "vhdl_fmt.sh"

[[language]]
name = "typescript"
roots = ["deno.json", "deno.jsonc", "package.json"]
auto-format = true
language-servers = ["deno-lsp"]

[[language]]
name = "javascript"
roots = ["deno.json", "deno.jsonc", "package.json"]
auto-format = true
language-servers = ["deno-lsp"]

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
config.deno.enable = true

# fix for:  https://github.com/tamasfe/taplo/issues/320
# sol from: https://github.com/tamasfe/taplo/issues/580#issuecomment-2004174721
[[language]]
name = "toml"
roots = ["."]

[[language]]
name = "just"
formatter = { command = "ec2hx", args = ["trim-trailing-whitespace"] }
auto-format = true

[[language]]
name = "bash"
indent = { unit = "    ", tab-width = 4 }
formatter = { command = "ec2hx", args = ["trim-trailing-whitespace"] }
auto-format = true

[[language]]
name = "mail"
text-width = 72

[[language]]
name = "openscad"
auto-format = true
