[[language]]
name = "python"
auto-format = true
language-servers = ["pyrefly", "ruff"]

[[language]]
name = "vhdl"
formatter.command = "vhdl_fmt.sh"

[[language]]
name = "typescript"
roots = ["deno.json", "deno.jsonc", "package.json"]
auto-format = true
language-servers = ["deno-lsp"]

[[language]]
name = "javascript"
roots = ["deno.json", "deno.jsonc", "package.json"]
auto-format = true
language-servers = ["deno-lsp"]

[[language]]
name = "just"
formatter = { command = "sed", args = ["s/[[:space:]]\\+$//"] }
auto-format = true

[[language]]
name = "bash"
indent = { unit = "    ", tab-width = 4 }
formatter = { command = "sed", args = ["s/[[:space:]]\\+$//"] }
auto-format = true

[[language]]
name = "mail"
text-width = 72

[[language]]
name = "openscad"
auto-format = true

[[language]]
name = "git-commit"
rulers = [73]

[[language]]
name = "jjdescription"
rulers = [73]

# -------- language servers -------- #

[language-server.rust-analyzer]
config.cargo.targetDir = true
config.check.command = "clippy"
config.imports.granularity.group = "item"
config.rustfmt.extraArgs = ["+nightly"]

[language-server.pyrefly]
command = "pyrefly"
args = ["lsp"]

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
config.deno.enable = true
