[language-server.rust-analyzer]
config.check.command = "clippy"

[language-server.pylsp.config.pylsp.plugins]
pycodestyle.maxLineLength = 120
mccabe.enabled = false # cyclomatic complexity
# more pylsp config options:
# https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md

[[language]]
name = "vhdl"
formatter.command = "vhdl_fmt.sh"
