[general]
# import = ["~/.config/alacritty/themes/dayfox.toml"]

live_config_reload = true

# [colors]
# draw_bold_text_with_bright_colors = true

[font.normal]
family = "Adwaita Mono"

[window]
decorations = "none"
