[general]
# import = ["~/.config/alacritty/themes/vscode.toml"]
# import = ["~/.config/alacritty/themes/github_light_high_contrast.toml"]
# import = ["~/.config/alacritty/themes/dayfox.toml"]

live_config_reload = true

# [colors]
# draw_bold_text_with_bright_colors = true

[font.normal]
family = "RobotoMono Nerd Font"

[window]
decorations = "none"
