import = ["~/.config/alacritty/themes/vscode.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[font.normal]
family = "RobotoMono Nerd Font"

[window]
decorations = "none"

[shell]
program = "fish" # ensure shell env is present in zellij, e.g. $EDITOR
args = ["-c", "zellij"]
