format = """
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$jobs\
$cmd_duration\
$character
"""

# right_format = "$time"

add_newline = false

[username]
format = "[$user]($style) "

[git_branch]
style = "bold green"
format = '[$branch ]($style)'
truncation_length = 16

[git_status]
format = '[($all_status$ahead_behind )]($style)'

[cmd_duration]
min_time = 10_000

[character]
success_symbol = "[❯](bold white)"

[time]
format = "[$time]($style)"
time_format = "%k:%M"
disabled = false
